<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class RemedioFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'nome_remedio' => $this->faker->randomElement(['ABCIXimabe BUpivacaína',
            'AmiNOFILina CefaLOTina',
            'CarVEDilol',
            'BEVACizumabe',
            'BEVACizumabe',
            'CefOTAXima',
            'ALENTUzumabe',
            'CalciTRIOL',
            'AZITromicina CeFAZolina',
            'BUpivacaína',
            'Ácido FolÍNico',
            'BusPIRona',
            'AmiTRIPtilina CeFAZolina',
            'BromoCRIPTINA',
            'ALfentanila',
            'CARBOplatina',
            'BETAmetasona CeFAZolina',
            'HaloPERidol',
            'OXALiplatina',
            'ABCIXimabe',
            'DACLizumabe',
            'CeFAZolina',
            'ALENTUzumabe',
            'PACLitaxel',
            'AZITromicina CefOTAXima',
            'BromoCRIPTINA',
            'Ácido FolÍNico',
            'BusPIRona',
            'AmiNOFILina CefTRIAXona',
            'BASILiximabe',
            'TRAStuzumabe',
            'CefTAZidima',
            'BEVACizumabe',
            'OXcarbazepina',
            'BEVACizumabe CefTAZidima',
            'GANciclovir',
            'BEVACizumabeABCIXimabe BUpivacaína',
            'AmiNOFILina CefaLOTina',
            'CarVEDilol',
            'BEVACizumabe',
            'BEVACizumabe',
            'CefOTAXima',
            'ALENTUzumabe',
            'CalciTRIOL',
            'AZITromicina CeFAZolina',
            'BUpivacaína',
            'Ácido FolÍNico',
            'BusPIRona',
            'AmiTRIPtilina CeFAZolina',
            'BromoCRIPTINA',
            'ALfentanila',
            'CARBOplatina',
            'BETAmetasona CeFAZolina',
            'HaloPERidol',
            'OXALiplatina',
            'ABCIXimabe',
            'DACLizumabe',
            'CeFAZolina',
            'ALENTUzumabe',
            'PACLitaxel',
            'AZITromicina CefOTAXima',
            'BromoCRIPTINA',
            'Ácido FolÍNico',
            'BusPIRona',
            'AmiNOFILina CefTRIAXona',
            'BASILiximabe',
            'TRAStuzumabe',
            'CefTAZidima',
            'BEVACizumabe',
            'OXcarbazepina',
            'BEVACizumabe CefTAZidima',
            'GANciclovir',
            'BEVACizumabe',]),
            //======================================================================//
            'formula' => $this->faker->randomElement(['Abacavir',
            'Abatacepte',
            'Abciximabe',
            'Abemaciclibe',
            'Acalabrutinibe',
            'Acarbose',
            'Acebrofilina',
            'Aceclofenaco',
            'Aceponato de Metilprednisolona',
            'Bacillus Clausii',
            'Bacillus cereus',
            'Bacitracina + Neomicina + Zinco',
            'Baclofeno',
            'Bacopa monnieri',
            'Baricitinibe',
            'Baryta carbonica + Atropa belladona',
            'Baryta carbonica + Berberis vulgaris + Calcarea carbonica + Mercurius sulphuratus ruber',
            'Baryta carbonica + Calcarea iodata + Thuya occidentalis + Agraphis nutans',
            'Baryta muriatica + Ambra grisea + Conium maculatum + Lycopodium clavatum',
            'Basiliximabe',
            'Belatacepte',
            'Cabazitaxel',
            'Cabergolina',
            'Cafeína + Carisoprodol + Diclofenaco Sodico + Paracetamol',
            'Cafeína + Carisoprodol + Paracetamol',
            'Cafeína + Di-hidroergotamina + Metoclopramida + Paracetamol',
            'Cafeína + Mesilato de Diidroergotamina + Paracetamol',
            'Dacarbazina',
            'Daclatasvir',
            'Dactinomicina',
            'Dalteparina Sodica',
            'Danazol',]),
            //==========================================================//
            'validade' => $this->faker->date('m/Y'),
            'nome_marca' => $this->faker->randomElement(['IAGEN',
            'TYMLOS',
            'ORENCIA',
            'REOPRO',
            'PRECOSE',
            'SECTRAL',
            'DIAMOX',
            'ACETADOTE',
            'SORIATANE',
            'TUDORZA PRESSAIR',
            'ZOVIRAX',
            'HUMIRA',
            'DIFFERIN',
            'HEPSERA',
            'ADENOCARD',
            'EYLEA',
            'FABRAZYME',
            'ALBENZA',
            'TANZEUM',
            'PROVENTIL-HFA ',
            'VENTOLIN-HFA',
            'LASTACAFT',
            'PROLEUKIN',
            'ALECENSA',
            'CAMPATH',
            'FOSAMAX',
            'UROXATRAL',
            'PRALUENT',
            'ZYLOPRIM',
            'AXERT',
            'NESINA',
            'LOTRONEX',
            'ACTIVASE',]),
            'lote' => $this->faker->randomNumber(3),
            'valor' => $this->faker->randomFloat(1,20,30),
            
        ];
    }
}
